# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fabf509cdeae222e9aa656edf2a6e387249c48776add0ab1feb7a92a9d674a4759e62bce18f152d30d869325f1b3388603f52d4340078e78adf268d4d5bf8cfe

test:
  secret_key_base: 4d1b8011b4ac74eb0248b34425aede94da2350809a52967a924a834851a3c7d5620aae11f6e321ab289d654491834d613879bdd2dae1cc0bc87e2156327737f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
